### ISSUE TITLE
data_packs vignette still huge

### ISSUE THREAD

**Issue by Robinlovelace** [udsleeds/openinfra#128]
Just about to share this with people but hesitant after opening it up and seeing this: 

![image](https://user-images.githubusercontent.com/1825120/188184674-da9599e0-e333-43b8-a8d9-6ccf6966789d.png)

https://udsleeds.github.io/openinfra/articles/data_packs.html#example-data-pack-production---leeds

That's still a huge amount of data. Can we make the dataset size smaller? 500 m should be fine.

**Comment by hulsiejames** [comment]
This (example plot sizes) should have been reduced considerably since this issue.

Think the main issue was that, for every plot after the default one pictured above, I had been using the entire west-yorkshire network resulting in long load times for the plots as opposed to a buffer around Leeds City Centre. 

This has now been reduced to (2-2.5Km I think!) and seems to load much faster (at least for mysely) now, although this laptop and city internet would definately help! 

Let me know if this is still taking too long to load as I can reduce the buffer size further. Likely, this will need to be done as we increase the number of example function outputs thus html maps hosted. 

(Noteably splitting the IM function #129 into 6/7 independant functions will require and additional 6/7 plots to visualise the outputs, being covered by [split_IM_function.R](https://github.com/udsleeds/openinfra/blob/main/test-code/split_IM_function.R))

**Comment by Robinlovelace** [comment]
This is now a good balance between benefits of seeing lots of examples vs benefits of fast load time. So closing for now, great work James!
