### ISSUE TITLE
Set-up project website

### ISSUE THREAD

**Issue by Robinlovelace** [udsleeds/openinfra#3]
This should be possible to do with a single R command:

```r
library(usethis)
use_pkgdown()
```

The subsequent commands should publish a website...

```r
use_pkgdown_github_pages()
use_github_action("pkgdown") 
```

More info: https://usethis.r-lib.org/reference/use_pkgdown.html

**Comment by GretaTimaite** [comment]
Published a [website](https://udsleeds.github.io/openinfra/), however I'm not happy with it at all. The home page does not display an image even though the [readme.md](https://github.com/udsleeds/openinfra/tree/gh-pages) finds it. I cannot figure out why it's a case because everything was fine when I built a [test website ](https://gretatimaite.github.io/web/) on my GH. So I might just delete all the files from the gh-pages branch and launch the website again in case there is a bug.

**Comment by Robinlovelace** [comment]
Great, we can definitely get this going :rocket:

**Comment by GretaTimaite** [comment]
> Published a [website](https://udsleeds.github.io/openinfra/), however I'm not happy with it at all. The home page does not display an image even though the [readme.md](https://github.com/udsleeds/openinfra/tree/gh-pages) finds it. I cannot figure out why it's a case because everything was fine when I built a [test website ](https://gretatimaite.github.io/web/) on my GH. So I might just delete all the files from the gh-pages branch and launch the website again in case there is a bug.

Seems like the issue [has been solved](https://udsleeds.github.io/openinfra/). I have checked out how `osmextract` has been built and noticed that there's no docs folder (might have been hidden?) and that all the files that should be inside the /docs are at the root, so I did the same. Changed the source from /docs (the recommended one) to root and it's working now? 

Still have no clue why the image was not displayed on the site when it was built from the /docs (tried changing file path, etc. to no avail). Any ideas on the issue?

Will change the home page to the README that's on the main branch or do you have anything else that you'd like to see on the home page for now?
