### ISSUE TITLE
GitHub actions are failing and website is not being updated

### ISSUE THREAD

**Issue by Robinlovelace** [udsleeds/openinfra#37]

**Comment by GretaTimaite** [comment]
I don't get why I keep getting this issue today when merging: https://github.com/udsleeds/openinfra/pull/38/conflicts

**Comment by Robinlovelace** [comment]
Seems 'mergeable' to me from that link, I see:

![image](https://user-images.githubusercontent.com/1825120/153604316-7cdd4747-0d06-49df-839c-07120eec4976.png)

I suggest checking out the main branch and then working form that, e.g. with the following commands from a terminal. Regularly pushing will help diagnose issues early. 

```bash
git checkout main
git pull
```

**Comment by GretaTimaite** [comment]
at least this [vignette](https://udsleeds.github.io/openinfra/articles/osmintro.html) got updated...

Note sure why another [cannot find an image](https://github.com/udsleeds/openinfra/runs/5158851924?check_suite_focus=true#step:6:39)...

**Comment by GretaTimaite** [comment]
Just noticed that openinfra.Rmd vignette became ["Get Started"](https://udsleeds.github.io/openinfra/articles/openinfra.html), which I guess makes sense but I thought it will be listed as an article... Anyway, I'm glad it's deployed and seems to have images displayed (had to incorporate html as it just didn't find a path to images otherwise).

Now it's time to finish writing it.
