### ISSUE TITLE
Create files representing local and transport authorities

### ISSUE THREAD

**Issue by Robinlovelace** [udsleeds/openinfra#51]
- [x] Transport authorities
- [x] Local authority districts

As geojson files.

**Comment by hulsiejames** [comment]
Local authority districts already [done](https://github.com/udsleeds/openinfra/blob/main/data-small/lads_joined_2021.geojson)

**Comment by hulsiejames** [comment]
Plan - create vignette documenting the administrative boundaries used for transport planning

**Comment by hulsiejames** [comment]
[Here](https://github.com/udsleeds/openinfra/blob/main/data-small/regions_new.geojson) are the transport regions

**Comment by hulsiejames** [comment]
Created [vignette](https://udsleeds.github.io/openinfra/articles/regions.html) on downloading and visualising transport authorities (England) and LADs (UK & NI) with links to the interactive .geojson files from /small-data in the repo.

to-do: Rather than links to the interactive maps, embed these interactive maps into the vignette using tmap. Much like [Greta's vingette](https://udsleeds.github.io/openinfra/articles/getosm.html)

**Comment by Robinlovelace** [comment]
Good plan to embed them in interactive maps, that will look great and be more valuable to people reading the docs.

**Comment by GretaTimaite** [comment]
Fantastic progress @hulsiejames ! Let me know if you need any help :)

**Comment by Robinlovelace** [comment]
Job done on the specific issue, new issues can be opened on interactive maps etc. Closing now to keep the momentum up.
