### ISSUE TITLE
ResCompLeedsCon 2022

### ISSUE THREAD

**Issue by GretaTimaite** [udsleeds/openinfra#62]
I think ResCompLeedsCon 2022 could be a good conference to talk about data packs @hulsiejames and @Robinlovelace.

Submission link + description: [Make a submission now!](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.office.com%2FPages%2FResponsePage.aspx%3Fid%3DqO3qvR3IzkWGPlIypTW3y7U8gIAi6LpMg7rjkJ9mZ3tUQUtTM1JCRVgxTzBEWVRSSUJBMlQ1RU1ERy4u&data=05%7C01%7CG.Timaite%40leeds.ac.uk%7Cd164f437c43f4ba3532c08da487a8f36%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C1%7C0%7C637901988489513014%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gRzjei8IeHLvfct7R%2F04NPmmjDoGCT2zzELqcZ9pcFA%3D&reserved=0)

Deadline: **24 June**
Word count: max 200

===========

Today James and I had a quick chat that it could be beneficial for James to draft a submission on his own with our support, if needed. This is a good skill to practice as it might be useful in the future when trying to "sell" one's ideas. 

EDIT: I sound like I have a lot of experience writing abstracts but I do not! It's just that if you James need any help or you don't know where to start, don't hesitate to reach out.

**Comment by hulsiejames** [comment]
No expert, but much more than me @GretaTimaite! 

Many thanks, I'll have a look at this now!

**Comment by hulsiejames** [comment]
@GretaTimaite Yes Alex has replied!

It is only a sinlge session you get selected for but you can opt in for multiple options, I am in agreement re: 15 minute talks, but I will apply for both on the off chance they are full of 15 minute talks or have many submissions for it! 

Also thank you for your suggestions on a showcase talk - origionally I wanted to steer away from this are but as you've mentioned we can focus on specific parts.

Of intrest to me also is:
> Do you regularly use a really useful tool in Python or R you want to tell more people about?

With respect to: 
> We use numerous tools/packages ([osmextract](https://github.com/ropensci/osmextract), [pyrosm](https://github.com/HTenkanen/pyrosm/), [OSMnx](https://github.com/gboeing/osmnx)) to obtain data and perform our analysis.

assuming we can call OSMnx / pyrosm and osmextract tools (yes! in my opinon)


Going to create a draft for each rn and see which I prefer (may end up submitting both and letting the ResCompLeedsCon gods decide which, or both, or either gets selected for a talk)

**Comment by hulsiejames** [comment]
**Update:**
Abstract deadline has been postponed until July 1st.

I have written a draft abstract for both the research story and showcase talk sessions. 
These are currently both over the word count (30 and 55 *ish* respectively) but I think there may be some waffle in that could be cut out.
Any thoughts on additional points that could be added to either is much appreciated! (and to be honest, waffle that could be cut)
_________________________________________________
**Research Story Abstract:** (237 words)

OpenInfra (Open Infrastructure) is studying the utility of Open Street Map (OSM) data as evidence to better inform local policy decision and infrastructure development.  

We use numerous tools / computational packages within the python/R environments to obtain OSM data and perform our analysis, including but not limited to osmextract, pyrosm, simple features, and OSMnx. 

Whilst OSM has proved to be an extensive database on mapping the existence of network infrastructure (all types of roads, cycling paths, walking paths, e.t.c) one issue that has arisen is the inconsistent feature tagging used by OSM mappers resulting in (a) a disproportionate number of ways with no additional tags other than way specification (road, cycle path etc.) and (b) inconsistent tagging practice among OSM mappers, for example querying highway=”cycleway” does not return all cycleways, a number of additional tags must be specified to define complete networks, which can become counterintuitive and rather confusing. 

Thus far the project has been able to produce reproducible documentation on the acquisition and analysis of OSM data for both Python and R. We have also developed a function in R that recategorizes OSM features based on whether they are compliant with the Inclusive Mobility (DfT) guide. 

The future of the OpenInfra project is focused on the upscaled production of such transport infrastructure data packs for every transport authority within Great Britain whilst maintaining the production of reproducible documentation on the acquisition and analysis of OSM data. 

_________________________________________________
**Showcase Talk:** (263 words)

Open Street Map (OSM) is widely used in transport research. However, its potential for planning infrastructure development is yet to be explored. OpenInfra hopes to explore the utility of OSM data as evidence to support decision making and local infrastructure development.  

Whilst there are many intuitive tutorials demonstrating how to add data to the OSM project, there is a distinct lack of material relating to how to acquire and work with OSM data. Making OSM data more accessible is one of the main objectives behind the OpenInfra project, thus we have explored several ways of interacting with OSM data in a reproducible manner.  

We have investigated several packages for acquiring and analysing geospatial OSM data, including osmextract (R), pyrosm & OSMnx (Python). Whilst these packages are effective in acquiring and analyzing OSM data, we have experienced some challenges - such as inconsistent levels of package documentation detail, and package bugs which can hinder analysis, especially as these packages typically have only one or two main contributors, working part-time. 

OSM has the potential to encourage local participatory planning, an approach that is considered crucial for inclusive design. If we want infrastructure to be accessible to all we must ask those who wish to use it, OSM can help enable this! 

It is of upmost importance to the OpenInfra project that our research and analysis be as reproducible as possible so that it is transparent and easy to learn from and should members of the public wish to re-create any analysis we have done (as a concerned citizen, or someone who wants to learn more!)

**Comment by GretaTimaite** [comment]
@hulsiejames, I'm going to focus on the Showcase Talk for now but I think some comments could be applicable to the research story too.  
> Open Street Map (OSM) is widely used in transport research. However, its potential for planning infrastructure development is yet to be explored. OpenInfra hopes to explore the utility of OSM data as evidence to support decision making and local infrastructure development.

OpenStreetMap is written without spaces...
I think there's a need for a smoother transition to OpenInfra project. It might be enough to add "Given this, OpenInfra project aims to...", but this is totally up to you.

> Whilst there are many intuitive tutorials demonstrating how to add data to the OSM project, there is a distinct lack of material relating to how to acquire and work with OSM data. Making OSM data more accessible is one of the main objectives behind the OpenInfra project, thus we have explored several ways of interacting with OSM data in a reproducible manner.

I think here you could mention, maybe as an opening sentence, that the main goal behind OI is to create data packs for each local authority but also that we acknowledge the importance of skills to work with OSM. Hence, as part of the project we...

Maybe you don't need "thus ..." because you repeat this in the next para with much more clarity.

> We have investigated several packages for acquiring and analysing geospatial OSM data, including osmextract (R), pyrosm & OSMnx (Python). Whilst these packages are effective in acquiring and analyzing OSM data, we have experienced some challenges - such as inconsistent levels of package documentation detail, and package bugs which can hinder analysis, especially as these packages typically have only one or two main contributors, working part-time.

Good discussion of limitations. I like your point on the contributors, however the formulation looks problematic as it begs question "To which package are you referring exactly?" I think it could be reformulated in a more (sociological?) manner. E.g., "... hinder analysis. Indeed, these issues might be resulting from the often invisible yet time-consuming labour required to maintain open source packages."

However, I'm also not sure if this point is really needed here even if important. Because it's not something we're looking into. Unless we want to raise awareness and ask people to contribute whenever they can?

> OSM has the potential to encourage local participatory planning, an approach that is considered crucial for inclusive design. If we want infrastructure to be accessible to all we must ask those who wish to use it, OSM can help enable this!

This looks a bit off in a sense that it does not stem nicely from your previous paragraph. I think it could be reformulated to link the importance of open tools for planning. 

Also my personal suggestion is to avoid emotional remarks in the academic abstracts.

> It is of upmost importance to the OpenInfra project that our research and analysis be as reproducible as possible so that it is transparent and easy to learn from and should members of the public wish to re-create any analysis we have done (as a concerned citizen, or someone who wants to learn more!)

I think this paragraph could be omitted.

I'd been thinking while reading this that it would be nice to mention how you'd showcase it exactly. It could be a vignette you wrote, some live demo/coding. I think it would be good to mention this as it would clarify our intention for applying for a showcase rather than a research story.

Good job and I hope it helps!

**Comment by hulsiejames** [comment]
> maybe you can open the abstract with OpenInfra and then -> OSM being used in transport research -> potential in planning infra.

I like this re-structure and think it flows well. 

>Indeed, these issues might be resulting from the often invisible yet time-consuming labour required to maintain open source packages."
However, I'm also not sure if this point is really needed here even if important. Because it's not something we're looking into. Unless we want to raise awareness and ask people to contribute whenever they can?

I think the ending will flow better as:
"Indeed, such issues are likely the result of time-consuming labour required to develope and maintain such open source packages."  as you suggest. 
I suppose with this statement we are both acknowledging and raising awareness and implying there is a need for colaboration on such projects.

>This looks a bit off in a sense that it does not stem nicely from your previous paragraph. I think it could be reformulated to link the importance of open tools for planning.

Maybe I could move this to come after paragraph 2? resturcturing may become clear there.

> I think this paragraph could be omitted.

Removed it! was wasting a few words and have already mentioned reproducibility. 

>I'd been thinking while reading this that it would be nice to mention how you'd showcase it exactly. It could be a vignette you wrote, some live demo/coding. I think it would be good to mention this as it would clarify our intention for applying for a showcase rather than a research story.

From the submission the format will be whichever option I select (can be talks or a poster talk) but I feel a presentation would be what we go for. I've updated the showcase talk abstract now apart from the final paragraph, issue is we are already 47 words over the limit (@ 247 now) so probably need to be cutting more things than adding at this point. 

Doing some work on LIDA SS slides for tomorrow then I will update the reasearch story abstract, I feel this may be a better fit but will update later!

**Comment by GretaTimaite** [comment]
@hulsiejames just a thought on showcase. Would it be interesting to quickly demonstrate how (if it's a case) each package returns a different cycling network and discuss how it might impact further analysis (it could be in terms of dataset size, network coherence, etc.)?

**Comment by hulsiejames** [comment]
> @hulsiejames just a thought on showcase. Would it be interesting to quickly demonstrate how (if it's a case) each package returns a different cycling network and discuss how it might impact further analysis (it could be in terms of dataset size, network coherence, etc.)?

@GretaTimaite Great point - I was actually thinking about this this morning and think it wouold be a graet thing to add! 

Though one thought I did have, I must be using the same dataset across each package so that the assessment is fair! 
(I know [OSMnx](https://github.com/gboeing/osmnx) typically [makes requests](https://osmnx.readthedocs.io/en/stable/index.html?highlight=API#usage) through [Nominatim](https://nominatim.org/), but there is an option (OSMnx) to read direct from [XML (.osm)](https://osmnx.readthedocs.io/en/stable/osmnx.html?highlight=data%20from%20XML%20#osmnx.graph.graph_from_xml) )

**Comment by GretaTimaite** [comment]
@hulsiejames I've edited your abstract. Cut off some words and sentences and added this:
> In this talk some of these issues will be demonstrated and potential solutions discussed, such as considering multi-programming language approach. 

I am thinking this way:
Problem: it's hard to download OSM data using Python
Solution: use R and move back to Python for further processing, thus multi-programming language approach (not sure it's a term though)

You can edit/delete this if you don't see the talk going this way.
By the way, currently it's 200 words.

**Comment by GretaTimaite** [comment]
@hulsiejames I believe you said it's submitted. Time to close this?

**Comment by hulsiejames** [comment]
Agreed. Abstract has been submitted and currently awaiting reply. 

I can re-open this when we get an update, or likely create a new issue if needed.
