### ISSUE TITLE
Getting work out there and adding social media links

### ISSUE THREAD

**Issue by Robinlovelace** [udsleeds/openinfra#64]
Follow-on from recent chat with @hulsiejames, the work can only have impact if people know about it. Lots of people know about it after this tweet https://twitter.com/robinlovelace/status/1498952906015264769 which I think led to its mention a very popular project: https://twitter.com/mszll/status/1527233843459145729

What's our social media strategy? I do recommend getting twitter accounts to put your work out there guys, you can tag me and LIDA to RT it and build interest. 

Also, at a minimum, we should add links to existing uses of the project as a kind of 'testimonials' page, maybe like this (although early days):  https://geocompr.github.io/guestbook/

**Comment by hulsiejames** [comment]
Sounds good! 

I will set up a twitter account now and follow LIDA and yourself, I will polish up a couple of the articles and then promote them through that.

I like the sound of this (early days as you day). Could this be set up as its own vignette article, perhaps "OpenInfra Reach"? 
I think we could include the credit for this project?  https://geocompr.github.io/guestbook/

**Comment by Robinlovelace** [comment]
Great stuff, let me know when you're online and I'll start following you and retweeting your stuff. Same with you Greta, Twitter is a good way of sharing your work + thoughts, just don't get sucked in and don't do 'doom scrolling'!

**Comment by GretaTimaite** [comment]
> Same with you Greta, Twitter is a good way of sharing your work + thoughts, just don't get sucked in and don't do 'doom scrolling'!

I created an account maybe a few weeks ago but did I use it since then? Nope. Really need to step up my game but I'm lazy when it comes to social media, so I'm really impressed by how much you consider these things. 

I've been keeping the track of the [presentations given](https://gretatimaite.netlify.app/presentation/) as part of the project on my personal website, so more than happy to move them to OpenInfra's website as I see you have a section on this (which makes sense) on geocompr website.

Collecting tweets as testimonials is also very clever. This reminded me that a few weeks ago I had a chat with Kylie about the project. She's very pleased with the project (the work we do in terms of research + engagement and how well the project reflects the values of LIDA), so she asked if I thought it was fine for her to get us in touch with Emily, our research impact officer, to take it further (not sure what exactly she meant by this). I, obviously, agreed but I have not heard from her since, however it was a busy period of recruiting a new cohort of data scientists. This might not be much in terms of purely data science impact but might help to get funding for another data scientist next year if that's in your plans ;)

**Comment by GretaTimaite** [comment]
Trying to figure out how @Robinlovelace built https://geocompr.github.io/ 
Looks like github pages + hugo + blogdown? 
I thought that if it's similar to how I built my [personal website with netlify + hugo + blogdown](https://gretatimaite.netlify.app/) (I still need to sort out domain name), then I could try to do something of this sort for the project, if needed. 

this comment is very much a follow-up on this:
> Also, at a minimum, we should add links to existing uses of the project as a kind of 'testimonials' page, maybe like this (although early days): https://geocompr.github.io/guestbook/

**Comment by Robinlovelace** [comment]
> Looks like github pages + hugo + blogdown?

Just blogdown will do it, that can install hugo and works will with web hosting companies like Netlify, but yes!
