### ISSUE TITLE
Fix actions

### ISSUE THREAD

**Issue by Robinlovelace** [udsleeds/openinfra#73]
Currently they are failing. Looking at the actions it seems they started failing when the dataset was added: https://github.com/udsleeds/openinfra/commits/main

Good practice is to test locally and commit any potentially breaking changes as PRs to test. Happy to help debug this @hulsiejames and happy to say: the solution is probably easier than you think!

**Comment by hulsiejames** [comment]
On it, I might need some help dubugging @Robinlovelace if available today! 

Follwoing your link to strplanr and mention of NAMESPACE in #71, I have tried to implement this. 

1. I went to data.R and added #'@export, like we did with recode_road_class, before running `devtools::document()` to update the NAMESPACE file.
2. Ran `devtools::run_examples()` after updating NAMESPACE above, and the example is still failing as data is not being loadaded in, but a character vector of the variable name "data_example". Additionally, I have some extra warnings: 
```
> print(structure(example_data))
[1] "example_data"

> output = recode_road_class(example_data)
Error in UseMethod("mutate") : 
  no applicable method for 'mutate' applied to an object of class "character"
In addition: Warning messages:
1: In setup_ns_exports(path, export_all, export_imports) :
  Objects listed as exports, but not present in namespace: example_data
2: In setup_ns_exports(path, export_all, export_imports) :
  Objects listed as exports, but not present in namespace: example_data
ℹ Loading openinfra
Warning message:
In setup_ns_exports(path, export_all, export_imports) :
  Objects listed as exports, but not present in namespace: example_data
```

Which has confused me since example_data has now been referenced by NAMESPACE after `devtools::document()`
```
# Generated by roxygen2: do not edit by hand

export("%>%")
export(example_data)
export(recode_road_class)
importFrom(magrittr,"%>%")
```

Also, after looking at the linked strplanr repo, I notice that R/data.R has a different format to [Openinfra's ](https://github.com/udsleeds/openinfra/blob/main/R/data.R), namely that the final line of each dataset is `NULL` rather than the name of a the variable as a string "example_data" as promted by [this video](https://youtu.be/BHgNA1vJO_0?t=607) following your google search post in #71 yesterday.

This might explain why calling `data(example_data)` is returning the character vector "example_data" in `devtools::check()` and the GH actions.

Finally, on package NAMESPACE, I notice that none of the [strplanr .Rda data ](https://github.com/ropensci/stplanr/tree/master/data) is referecned in the [NAMESPACE ](https://github.com/ropensci/stplanr/blob/8a9c7b5a9309c48a542e157205fdaff1ddee120e/NAMESPACE) (for exmaple, `zones_sf`, `route_network_sf`)

Current thoughts are that I should probably not have @export within the `data.R` file, as strplanr does not, but a little stumped apart from that.

**Comment by hulsiejames** [comment]
Okay, acutally I think I've fixed and as you said easier than first seems!

After writing the above I was totally stumped and went to try debug using my mac.

Reinstalled the latest version with `devtools::install_github("udsleeds/openinfra")`

Then ran the following: 

```
library(openinfra)

test1 = openinfra::exmaple_data 
test2 = example_data 
test3 = data(example_data)
```

Which provided
```
test1: (36065, 16) frame
test2: (36065, 16) frame
test3: "example_data"
```

It seems `data()` was the issue, calling just `example_data` has worked - I'm not sure if this is what you were referencing as being the easier fix than expected? I still don't quite understand a couple of the discrepencies between the strplanr and openinfra data documentation, but at least actions are now passing.

**Comment by Robinlovelace** [comment]
> It seems `data()` was the issue, calling just `example_data` has worked - I'm not sure if this is what you were referencing as being the easier fix than expected?

Correct. Sounds like progress and great work! I guess we can close this issue now but can always reopen if any further issues arise.

**Comment by hulsiejames** [comment]
failing again atm - debugging this. 

`devtools::run_examples()` is passing locally.

`devtools::check()` is not - nor are actions. 
Error is as follows: 
```
  > library(openinfra)
  > u_data_large = paste0("https://github.com/udsleeds/openinfra/releases",
  +                       "/download/v0.2/bbbike_leeds_27_6_22.geojson")
  > u_data_small = paste0("https://github.com/udsleeds/openinfra/releases",
  +                       "/download/v0.2/30_06_22_bbbike_LCC_func_example_5_75km.geojson")
  > #example_data = sf::read_sf(u_data_small)
  > #print(structure(example_data))
  > internal_data = example_data
  > output = recode_road_class(internal_data)
  Error in `vec_size()`:
  ! `x` must be a vector, not a <sfc_LINESTRING/sfc> object.
  Backtrace:
       ▆
    1. ├─openinfra::recode_road_class(internal_data)
    2. │ └─... %>% dplyr::filter(!is.na(road_class))
    3. ├─dplyr::filter(., !is.na(road_class))
    4. ├─dplyr:::filter.data.frame(., !is.na(road_class))
    5. │ ├─dplyr::dplyr_row_slice(.data, loc, preserve = .preserve)
    6. │ └─dplyr:::dplyr_row_slice.data.frame(.data, loc, preserve = .preserve)
    7. │   ├─dplyr::dplyr_reconstruct(vec_slice(data, i), data)
    8. │   │ └─dplyr:::dplyr_new_data_frame(data)
    9. │   │   ├─row.names %||% .row_names_info(x, type = 0L)
   10. │   │   └─base::.row_names_info(x, type = 0L)
   11. │   └─vctrs::vec_slice(data, i)
   12. └─vctrs:::stop_scalar_type(`<fn>`(`<s_LINEST>`), "x", `<fn>`(vec_size()))
   13.   └─vctrs:::stop_vctrs(...)
   14.     └─rlang::abort(message, class = c(class, "vctrs_error"), ..., call = vctrs_error_call(call))
  Execution halted
```

**Comment by Robinlovelace** [comment]
Maybe you need to add `library(sf)` into the code under `@examples`

**Comment by hulsiejames** [comment]
Trying to try this now - currently running `devtools::check()` which is failing on vignette building. 

I don't know if this is just a local issue to me, or would fail if pushed to GH so as suggested just trying to get all checks running locally before I push.
